### ISSUE TITLE
Can't create batch iterator

### ISSUE THREAD

**Issue by ymym3412** [chakki-works/chariot#6]
I create DataSetPreprocessor for Japanese document, and then call iterate() but get error.  
`ValueError: Cannot take a larger sample than population when 'replace=False'`

I run following code. 
`train_df` has three columns `article` `title` `label` .
```py
dp = DatasetPreprocessor()
dp.process('article')\
    .by(ct.text.UnicodeNormalizer())\
    .by(ct.Tokenizer('ja'))\
    .by(ct.token.StopwordFilter('ja'))\
    .by(ct.Vocabulary(min_df=5, max_df=0.5))\
    .by(Padding(length=pad_length))\
    .fit(train_df['article'])

dp.process('label')\
    .by(ct.formatter.CategoricalLabel(num_class=9))

preprocessed = dp.preprocess(train_df)

for b in dp.iterate(preprocessed, batch_size=8, epoch=10):
    print(b)
```

I guess this is because DataSetPreprocessor.iterate() calc `data_length` from `len(_data)` but _data is dict.

**Comment by icoxfog417** [comment]
Thank you for reporting the issue! This bug will be fixed by `0.5.1`
