### ISSUE TITLE
Can I make a filter to drop data by some conditions?

### ISSUE THREAD

**Issue by knok** [chakki-works/chariot#9]
I am trying to use chariot.
My raw csv data has some needless lines, so I'll try to remove them.
It seems that Formatter class handles whole data, but it should be handle
single column, so it wouln't be fit to my purpose, right?

For example:

|source|target|
--------|-------
|abc |def|
|fgh|xyz|
|...|....|

I just want to remove 2nd line (fgh, xyz) with a condition like re.match(r'z$', line['target'])

**Comment by icoxfog417** [comment]
`chariot` does not have the row filtering feature now. So you have to filter the data before applying the preprocessing.
